### ISSUE TITLE
Request for update of mdast-util-from-markdown dependency to latest version

### ISSUE THREAD

**Issue by zsh-eng** [landakram/mdast-util-wiki-link#6]
Currently, the project relies on the `mdast-util-from-markdown` package for markdown parsing functionality. However, it appears that the project is using an outdated version of `mdast-util-from-markdown`.

In projects that use the latest version of `mdast-util-from-markdown`, this extension is broken due to changes to the default exports as well as changes to the `enter` and `exit` functions (see this [commit](https://github.com/syntax-tree/mdast-util-from-markdown/commit/18f4bb0f1b720fd30f1c3a7b11e1fac90aa6903f?diff=split)).

I would like to request an update to the latest version of `mdast-util-from-markdown` (2.0.0 at the time of writing) from 0.8.0. If you are open to accepting contributions, I am willing to submit a pull request with the necessary changes. Thank you!

**Comment by landakram** [comment]
Thanks for raising this issue. 

I’m very open to contributions so please feel free to make a PR!

**Comment by landakram** [comment]
closed with https://github.com/landakram/mdast-util-wiki-link/pull/8
